### ISSUE TITLE
Print times in 12-hour format instead of 24-hour format

### ISSUE THREAD

**Issue by rickygv99** [stanford-oval/thingtalk#140]
Since our target audience is American consumers right now, we should default to printing times in 12-hour format (e.g. 09:00 AM and 10:00 PM) instead of 24-hour format (e.g. 09:00 and 22:00). The American public is more used to 12-hour format; 24-hour format is primarily used in internal military and scientific applications. We can include an option to print times in 24-hour format instead but default should be 12-hour format instead of 24-hour format.

**Comment by gcampax** [comment]
ThingTalk uses [Date.toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString) and related methods to format times and dates. These are locale sensitive, but you might need to install the correct localization data. At least on my system, it uses 12-hour format already.

**Comment by rickygv99** [comment]
Could we install the localization data on Web Almond?

**Comment by gcampax** [comment]
Localization data is installed on Web Almond already, and "what time is it" displays in the correct format. Yet times in confirmation strings are not shown in 12 hour format, so it is a thingtalk bug.

**Comment by gcampax** [comment]
Found the bug

**Comment by gcampax** [comment]
The fix hasn't landed yet, don't close this.
