### ISSUE TITLE
Introduce a new generic degrees unit

### ISSUE THREAD

**Issue by balloob** [stanford-oval/thingtalk#183]
Thingtalk currently uses the used locale to decide if the user means Celsius or Fahrenheit when they mention a sentence with the word "degrees" (ie Set thermostat to 23 degrees).

However, that assumption is not always safe to make. Instead, we should introduce a new generic degrees unit. This allows the Thingtalk interpreter to decide if it's C or F based on the user preferences or other context.

Overview of required changes by @gcampax:

- modify https://github.com/stanford-oval/thingtalk/blob/b4965a7ce88fd349dfb460c17ec0185f811dbbaa/lib/ast/values.js#L310 to recognize the new pseudo-unit and call the unit conversion library with the right value
- modify https://github.com/stanford-oval/thingtalk/blob/b4965a7ce88fd349dfb460c17ec0185f811dbbaa/lib/describe.js#L253 to describe the value with that unit correctly
- modify https://github.com/stanford-oval/genie-toolkit/blob/86b90021119668c66cdc83e91778cad1cc80112d/languages/thingtalk/en/constants.genie#L86 to map "degrees" to the new pseudo-unit instead of "F"

**Comment by gcampax** [comment]
This was fixed in #187
