### ISSUE TITLE
Running functions of thingpedia.tt from terminal

### ISSUE THREAD

**Issue by vinith-reddy25** [stanford-oval/thingtalk#407]
How to run functions of thingpedia.tt like "@com.thecatapi.cat()" from terminal?

**Comment by rayslxu** [comment]
We don't have support for that, unfortunately. We used to have a command-line version of Almond/Genie ([github page](https://github.com/stanford-oval/almond-cmdline)), but we no longer update that, since we think genie-server is a better tool for testing and skill development.

**Comment by rayslxu** [comment]
Closing this, because it's not really an "issue"
